// Code generated by mockery v2.35.3. DO NOT EDIT.

package clustertool

import mock "github.com/stretchr/testify/mock"

// MockapplyFuture is an autogenerated mock type for the applyFuture type
type MockapplyFuture struct {
	mock.Mock
}

// Error provides a mock function with given fields:
func (_m *MockapplyFuture) Error() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Index provides a mock function with given fields:
func (_m *MockapplyFuture) Index() uint64 {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// Response provides a mock function with given fields:
func (_m *MockapplyFuture) Response() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// NewMockapplyFuture creates a new instance of MockapplyFuture. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockapplyFuture(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockapplyFuture {
	mock := &MockapplyFuture{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
