// Code generated by mockery v2.35.3. DO NOT EDIT.

package clustertool

import (
	raft "github.com/hashicorp/raft"
	mock "github.com/stretchr/testify/mock"
)

// MockconfigurationFuture is an autogenerated mock type for the configurationFuture type
type MockconfigurationFuture struct {
	mock.Mock
}

// Configuration provides a mock function with given fields:
func (_m *MockconfigurationFuture) Configuration() raft.Configuration {
	ret := _m.Called()

	var r0 raft.Configuration
	if rf, ok := ret.Get(0).(func() raft.Configuration); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(raft.Configuration)
	}

	return r0
}

// Error provides a mock function with given fields:
func (_m *MockconfigurationFuture) Error() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Index provides a mock function with given fields:
func (_m *MockconfigurationFuture) Index() uint64 {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// NewMockconfigurationFuture creates a new instance of MockconfigurationFuture. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockconfigurationFuture(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockconfigurationFuture {
	mock := &MockconfigurationFuture{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
