// Code generated by mockery v2.35.3. DO NOT EDIT.

package clustertool

import mock "github.com/stretchr/testify/mock"

// MockindexFuture is an autogenerated mock type for the indexFuture type
type MockindexFuture struct {
	mock.Mock
}

// Error provides a mock function with given fields:
func (_m *MockindexFuture) Error() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Index provides a mock function with given fields:
func (_m *MockindexFuture) Index() uint64 {
	ret := _m.Called()

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// NewMockindexFuture creates a new instance of MockindexFuture. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockindexFuture(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockindexFuture {
	mock := &MockindexFuture{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
