// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	clustertool "github.com/tscolari/clustertool"
)

// App is an autogenerated mock type for the App type
type App struct {
	mock.Mock
}

// Apply provides a mock function with given fields: cmd
func (_m *App) Apply(cmd []byte) error {
	ret := _m.Called(cmd)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Node provides a mock function with given fields:
func (_m *App) Node() clustertool.Node {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Node")
	}

	var r0 clustertool.Node
	if rf, ok := ret.Get(0).(func() clustertool.Node); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clustertool.Node)
		}
	}

	return r0
}

// SendQuery provides a mock function with given fields: name, payload, params
func (_m *App) SendQuery(name string, payload []byte, params *clustertool.QueryParam) (clustertool.EventResponse, error) {
	ret := _m.Called(name, payload, params)

	if len(ret) == 0 {
		panic("no return value specified for SendQuery")
	}

	var r0 clustertool.EventResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, []byte, *clustertool.QueryParam) (clustertool.EventResponse, error)); ok {
		return rf(name, payload, params)
	}
	if rf, ok := ret.Get(0).(func(string, []byte, *clustertool.QueryParam) clustertool.EventResponse); ok {
		r0 = rf(name, payload, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(clustertool.EventResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, []byte, *clustertool.QueryParam) error); ok {
		r1 = rf(name, payload, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubscribeToQuery provides a mock function with given fields: name, action
func (_m *App) SubscribeToQuery(name string, action func(clustertool.Query) error) error {
	ret := _m.Called(name, action)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeToQuery")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func(clustertool.Query) error) error); ok {
		r0 = rf(name, action)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewApp creates a new instance of App. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *App {
	mock := &App{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
